# Generated by Django 5.0.7 on 2024-07-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dedscription',
            new_name='description',
        ),
    ]
