# Generated by Django 5.0.7 on 2024-08-01 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_cart', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_intent_id',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecommerce_cart.shippingoption'),
        ),
    ]
